version: "3.8"
services:
  express:
    image: giftr-api
    container_name: giftr-api
    environment:
      API_JWTKEY: sp8cyj0fyns3zoj6aju5wffvlt3hj7
      API_PORT: 80
      NODE_ENV: "stage"
    ports:
      - 3030:80
    command: node server.js
